for(int i=n-1;i>=0;i--){
        if(s.empty()){
            v.push_back(-1);
            s.push(arr[i]);
        }
        else{
            while(!s.empty()){
                if(s.top()>arr[i]){
                    v.push_back(s.top());
                    break;
                }
                else{
                    s.pop();
                }
            }
            if(s.empty()){
                v.push_back(-1);
                s.push(arr[i]);
            }
        }
    }